version: '3'
services:

    bootstrap:
        image: raicoin
        environment:
            - RUNTIME_ARGS=--bootstrap --load length3.chain
        ports:
            - "0:6363"

    mining:
        image: raicoin
        environment:
            - RUNTIME_ARGS=--bootstrap --load length3.chain --mine
        ports:
            - "0:6363"
