version: '3'
services:

    bootstrap:
        image: raicoin
        environment:
            - RUNTIME_ARGS=--bootstrap --load length3.chain
        ports:
            - "0:6363"

    mining:
        image: raicoin
        environment:
            - RUNTIME_ARGS=--non-interactive --load length3.chain --mine --starting-peers=bootstrap
        ports:
            - "0:6363"

    island:
        image: raicoin
        environment:
            - RUNTIME_ARGS=--non-interactive --load length1.chain --starting-peers=mining
        ports:
            - "0:6363"
