version: '3'
services:

    bootstrap:
        image: raicoin
        environment:
            - RUNTIME_ARGS=--bootstrap

    peer:
        image: raicoin
        environment:
            - RUNTIME_ARGS=--non-interactive --starting-peers bootstrap
