version: '3'
services:

    bootstrap:
        build:
            context: .
            args:
                - runtime_args=--bootstrap
        container_name: bootstrap

    peer:
        build:
            context: .
            args:
                - runtime_args=--non-interactive --starting-peers bootstrap
        container_name: peer
